version: '2'

services:
    face-tracker:
        build: ./python-server/
        privileged: true
        devices:
          - "/dev/video0:/dev/video0"
        depends_on:
            - mosquitto
            - mongodb
        ports:
            - "8080:8080"
        tty: true

    #this container uses the "person monitor project" if you don't need this please comment out the next linex
    person-monitor:
        build: ../../person-monitor/docker-container
        depends_on:
            - mosquitto
        tty: true

    mosquitto:
        image: mosquitto
        build: ./mosquitto/
        ports:
            - "1884:1884"

    mongodb:
        image: dhermanns/rpi-mongo
        ports:
            - "27017:27017"